In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
Slice1 =arr[2:6]
print(Slice1)
Slice2=arr[::2]
print(Slice2)

[3 4 5 6]
[1 3 5 7 9]


In [19]:
rev_arr=arr[::-1]
print(rev_arr)

[9 8 7 6 5 4 3 2 1]


In [23]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[0:3:2])
print(a[0::2])
print(a[1::])
print(a[2:,2:])
print(a[:,2])
print(a[:2:3])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[11 12]]
[ 3  7 11]
[[1 2 3 4]]


In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


In [3]:
reversed_array=arr[::-1]
print(reversed_array)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [5]:
col1=arr[:,0]
print(col1)

[1 4 7]


In [7]:
row1=arr[0,:]
print(row1)

[1 2 3]


In [9]:
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[4])
print(arr[-1])
print([arr>25])
print(arr[[1,3]])

10
50
50
[array([False, False,  True,  True,  True])]
[20 40]


In [11]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
print(arr[1,2])

1
6


In [14]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [16]:
result1=np.vstack((arr1,arr2))
print(result1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [18]:
result2=np.dstack((arr1,arr2))
print(result2)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [34]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [5]:
arr1=np.array([1,2,3,4,5])
result1=np.arrray_split(arr(1,3))
print(result1)

AttributeError: module 'numpy' has no attribute 'arrray_split'