In [2]:
  import numpy as np
  a=np.array([1,2,3,4,5])
  print(a)

[1 2 3 4 5]


In [9]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [2]:
import numpy as np
c=np.zeros((3,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
d=np.random.random((2,2))
print(d)

[[0.54321478 0.47209625]
 [0.02807123 0.19403104]]


In [1]:
import numpy as np
e=np.arange(0,20,5)
print(e)

[ 0  5 10 15]


In [7]:
arr=np.array([[1,2,3,4],[5,6,7,8],[1,2,0,1]])
newarr=arr.reshape(4,3)
print(arr)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[[1 2 3]
 [4 5 6]
 [7 8 1]
 [2 0 1]]


In [13]:
flat=arr.flatten()
print(arr)
print(flat)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)


[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[1 2 3 4 5 6 7 8 1 2 0 1]
2
(3, 4)
int64
12


In [15]:
newtype=arr.astype('f')
print("\n convert array : \n",newtype)
print("\n converted array type:\n",newtype.dtype)

                   


 convert array : 
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 2. 0. 1.]]

 converted array type:
 float32


In [19]:
size =len(arr)
print("\n size of array:\n",size) 


 size of array:
 3
